services:
  api:
    # At the time of writing, rasterio wheels are not available for arm64 arch
    # so we force the image to be built with linux/amd64
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: ["uvicorn", "titiler.eopf.main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "1"]
    environment:
      # GDAL Config
      # This option controls the default GDAL raster block cache size.
      # If its value is small (less than 100000), it is assumed to be measured in megabytes, otherwise in bytes.
      - CPL_TMPDIR=/tmp
      - GDAL_CACHEMAX=75%
      - GDAL_DISABLE_READDIR_ON_OPEN=EMPTY_DIR
      - GDAL_INGESTED_BYTES_AT_OPEN=32768
      - GDAL_HTTP_MERGE_CONSECUTIVE_RANGES=YES
      - GDAL_HTTP_MULTIPLEX=YES
      - GDAL_HTTP_VERSION=2
      # The file can be cached in RAM by setting the configuration option VSI_CACHE to TRUE.
      # The cache size defaults to 25 MB, but can be modified by setting the configuration option VSI_CACHE_SIZE (in bytes).
      # Content in that cache is discarded when the file handle is closed.
      - VSI_CACHE=TRUE
      - VSI_CACHE_SIZE=536870912
      # In addition, a global least-recently-used cache of 16 MB shared among all downloaded content is enabled by default,
      # and content in it may be reused after a file handle has been closed and reopen,
      # during the life-time of the process or until VSICurlClearCache() is called.
      # Starting with GDAL 2.3, the size of this global LRU cache can be modified by
      # setting the configuration option CPL_VSIL_CURL_CACHE_SIZE (in bytes).
      - CPL_VSIL_CURL_CACHE_SIZE=200000000
      # TiTiler Config
      # - RIO_TILER_MAX_THREADS=
      # AWS S3 endpoint config
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_REGION=${AWS_REGION}
      - AWS_ENDPOINT_URL=${AWS_ENDPOINT_URL}
      - TITILER_EOPF_STORE_SCHEME=s3
      - TITILER_EOPF_STORE_HOST=esa-zarr-sentinel-explorer-fra
      - TITILER_EOPF_STORE_PATH=tests-output
      - TITILER_EOPF_CACHE_HOST=cache
      - TITILER_EOPF_CACHE_ENABLE=True
    volumes:
      - ./:/data
    depends_on:
      - cache

  api-openeo:
    extends:
      service: api
    ports:
      - "8081:8081"
    environment:
      # GDAL Config
      # This option controls the default GDAL raster block cache size.
      # If its value is small (less than 100000), it is assumed to be measured in megabytes, otherwise in bytes.
      - CPL_TMPDIR=/tmp
      - GDAL_CACHEMAX=75%
      - GDAL_DISABLE_READDIR_ON_OPEN=EMPTY_DIR
      - GDAL_INGESTED_BYTES_AT_OPEN=32768
      - GDAL_HTTP_MERGE_CONSECUTIVE_RANGES=YES
      - GDAL_HTTP_MULTIPLEX=YES
      - GDAL_HTTP_VERSION=2
      # The file can be cached in RAM by setting the configuration option VSI_CACHE to TRUE.
      # The cache size defaults to 25 MB, but can be modified by setting the configuration option VSI_CACHE_SIZE (in bytes).
      # Content in that cache is discarded when the file handle is closed.
      - VSI_CACHE=TRUE
      - VSI_CACHE_SIZE=536870912
      # In addition, a global least-recently-used cache of 16 MB shared among all downloaded content is enabled by default,
      # and content in it may be reused after a file handle has been closed and reopen,
      # during the life-time of the process or until VSICurlClearCache() is called.
      # Starting with GDAL 2.3, the size of this global LRU cache can be modified by
      # setting the configuration option CPL_VSIL_CURL_CACHE_SIZE (in bytes).
      - CPL_VSIL_CURL_CACHE_SIZE=200000000
      # TiTiler Config
      # - RIO_TILER_MAX_THREADS=
      # AWS S3 endpoint config
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_REGION=${AWS_REGION}
      - AWS_ENDPOINT_URL=${AWS_ENDPOINT_URL}
      - TITILER_OPENEO_STAC_API_URL=https://api.explorer.eopf.copernicus.eu/stac
      - TITILER_OPENEO_SERVICE_STORE_URL=/services/copernicus.json
      - TITILER_EOPF_CACHE_HOST=cache
      - TITILER_EOPF_CACHE_ENABLE=True
    command: ["uvicorn", "titiler.eopf.openeo.main:app", "--host", "0.0.0.0", "--port", "8081", "--workers", "1"]
    volumes:
      - ./services/:/services
    depends_on:
      - cache

  openeo:
    platform: linux/amd64
    image: mundialis/openeo-web-editor:latest
    ports:
      - "8082:80"
    env_file:
      - path: .env
        required: false
    depends_on:
      - api-openeo

  cache:
    image: redis:latest
    ports:
      - 6379:6379
