{{- if and .Values.redis.enabled .Values.redis.auth.enabled (not .Values.redis.auth.existingSecret) .Values.redis.auth.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "titiler-eopf.redis.fullname" . }}
type: Opaque
data:
  redis-password: {{ .Values.redis.auth.password | b64enc | quote }}
{{- end }}
